<a href="https://colab.research.google.com/github/IrinaKusyakinamew/LR6/blob/master/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Загрузка данных

https://www.kaggle.com/datasets/arashnic/hr-analytics-job-change-of-data-scientists

https://drive.google.com/file/d/11NzpmzB9sLYimFsjg_Kv3oO15kX5UFwS/view?usp=sharing

Включить режим горячих клавиш: Ctrl + M
После включения режима горячих клавиш можем использовать разные комбинации
1. Удалить блок: D
2. Вставить блок до/после текущего блока: B (Below: до); A (Above: после)
3. Превратить кодовую ячейку в текст: M (markdown, т.е. текстовая ячейка)
4. Превратить текст в кодовую ячейку: Y
5. Запуск ячейки: shift + enter (курсор переключится в след ячейку); ctrl + enter (курсор остается в текущей ячейке)

С помощью команды ниже загружаем ранее сохраненный zip-архив

In [1]:
! gdown --id 11NzpmzB9sLYimFsjg_Kv3oO15kX5UFwS

/usr/local/lib/python3.11/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=11NzpmzB9sLYimFsjg_Kv3oO15kX5UFwS
To: /content/archive.zip
100% 302k/302k [00:00<00:00, 80.6MB/s]

Распаковываем архив

In [2]:
! unzip /content/archive.zip

Archive:  /content/archive.zip
  inflating: aug_test.csv
  inflating: aug_train.csv
  inflating: sample_submission.csv

# Чтение данных

Перед началом работы необходимо импортировать библиотеку pandas

In [8]:
import pandas as pd

Затем создаем переменную df (от dataframe) и читаем в нее содержимое файла .csv, находящегося в папке ранее распакованного архива

In [10]:
df = pd.read_csv('/content/aug_train.csv')

Выводим таблицу в формате dataframe, хранящуюся внутри переменной df

In [11]:
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

Важно: для удобства работы следует называть переменную, хранящую таблицу, именно df

# Основные операции с датафреймом (таблицей)

Выводим первые 10 строк таблицы. Если не передать аргумент в head, по умолчанию выведутся первые 5 строк

In [22]:
df.head(10)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
5,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
6,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
7,402,city_46,0.762,Male,Has relevent experience,no_enrollment,Graduate,STEM,13,<10,Pvt Ltd,>4,18,1.0
8,27107,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,7,50-99,Pvt Ltd,1,46,1.0
9,699,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,17,10000+,Pvt Ltd,>4,123,0.0

Выводим последние 7 строк таблицы. Если не передать аргумент в tail, выведутся последние 5 строк

In [16]:
df.tail(7)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
19151,11385,city_149,0.689,Male,No relevent experience,Full time course,Graduate,NaN,2,NaN,NaN,1,60,0.0
19152,29754,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,Humanities,7,10/49,Funded Startup,1,25,0.0
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

Выводим часть таблицы как объект series:

In [20]:
df['city']

0        city_103
1         city_40
2         city_21
3        city_115
4        city_162
           ...
19153    city_173
19154    city_103
19155    city_103
19156     city_65
19157     city_67
Name: city, Length: 19158, dtype: object

Выводим часть датафрейма, заключив название столбца в дополнительные квадратные скобки:

In [18]:
df[['city']]

           city
0      city_103
1       city_40
2       city_21
3      city_115
4      city_162
...         ...
19153  city_173
19154  city_103
19155  city_103
19156   city_65
19157   city_67

[19158 rows x 1 columns]

Для обращения к нескольким столбцам таблицы необходимо указывать их в ДВОЙНЫХ КВАДРАТНЫХ СКОБКАХ. Обращение в одинарных скобках допустимо только к ОДНОМУ столбцу. Остальные варианты приведут к ошибкам

In [23]:
df[['city', 'gender', 'experience']]

           city gender experience
0      city_103   Male        >20
1       city_40   Male         15
2       city_21    NaN          5
3      city_115    NaN         <1
4      city_162   Male        >20
...         ...    ...        ...
19153  city_173   Male         14
19154  city_103   Male         14
19155  city_103   Male        >20
19156   city_65   Male         <1
19157   city_67    NaN          2

[19158 rows x 3 columns]

Во время работы в colab не нужно использовать print, у pandas для этого предусмотрено специальное оформление в colab. Print же будет выводить данные не очень приятным для глаза способом

In [24]:
print(df.head())

   enrollee_id      city  city_development_index gender  \
0         8949  city_103                   0.920   Male
1        29725   city_40                   0.776   Male
2        11561   city_21                   0.624    NaN
3        33241  city_115                   0.789    NaN
4          666  city_162                   0.767   Male

       relevent_experience enrolled_university education_level  \
0  Has relevent experience       no_enrollment        Graduate
1   No relevent experience       no_enrollment        Graduate
2   No relevent experience    Full time course        Graduate
3   No relevent experience                 NaN        Graduate
4  Has relevent experience       no_enrollment         Masters

  major_discipline experience company_size    company_type last_new_job  \
0             STEM        >20          NaN             NaN            1
1             STEM         15        50-99         Pvt Ltd           >4
2             STEM          5          NaN             NaN        never
3  Business Degree         <1          NaN         Pvt Ltd        never
4             STEM        >20        50-99  Funded Startup            4

   training_hours  target
0              36     1.0
1              47     0.0
2              83     0.0
3              52     1.0
4               8     0.0

Количество строк в датафрейме (таблице):

In [25]:
len(df)

19158